site:
  title: TL;DR
  start_page: tldr::index.adoc
content:
  sources:
    - url: .
      branches: [main]
ui:
  bundle:
    url: https://github.com/timothysparg/tldr-ui/releases/download/v1.1.0/ui-bundle.zip
output:
  dir: public
asciidoc:
  attributes:
    allow-uri-read: ""
