site:
  title: TL;DR
  start_page: tldr::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      worktrees: true
antora:
  extensions:
    - ./posts-extension.js
ui:
  bundle:
    url: https://github.com/timothysparg/tldr-ui/releases/download/v1.4.1/ui-bundle.zip
    # url: https://github.com/timothysparg/tldr-ui/releases/download/beta/ui-bundle.zip
    snapshot: true
output:
  dir: public
asciidoc:
  attributes:
    allow-uri-read: ""
