
[settings]
lockfile = true
experimental = true


[tools]
node = "lts"
"npm:antora" = "latest"
"npm:live-server" = "latest"
watchexec = "latest"

[tasks.build]
run = "antora --fetch antora-playbook.yml"
sources = ["antora-playbook.yml", "antora.yml", "posts-extension.js", "modules/**/*"]
outputs = ["public/**"]

[tasks.serve]
run = "live-server public --port=5959 --no-browser"

[tasks.watch-build]
run = "mise watch build"

[tasks.dev]
description = "Watch for changes, rebuild, and serve the site"
run = [
  { tasks = ["serve", "watch-build"] }
]
